feature/add-ErrorHandling
OnlySpans/PolyLeads pull request #88
Opened 2024-06-10 19:35 UTC by Chebarik

2024-06-11 21:13 UTC, BioShock23 requested changes

2024-06-11 21:13 UTC, BioShock23 commented on src/OnlySpans.PolyLeads.Api/Services/Exceptions/GlobalExceptionHandler.cs
> +                Detail = string.Join(".\n", ex.Errors),
а без string.Join() тут никак? посмотри, мб у ValidationException метод есть чтоб строку красивую выдавал

2024-06-11 21:14 UTC, BioShock23 commented on src/OnlySpans.PolyLeads.Api/Exceptions/RecognitionException.cs
> +    public RecognitionException(
ниже это в плане в этом же классе

2024-06-11 21:39 UTC, Chebarik commented on src/OnlySpans.PolyLeads.Api/Exceptions/RecognitionException.cs
> +    public RecognitionException(
да очепятка

2024-06-16 10:52 UTC, BioShock23 approved these changes

2024-06-16 10:53 UTC, merged