feature/llm-integration
OnlySpans/PolyLeads pull request #91
Opened 2024-06-22 10:51 UTC by Berkas721

2024-06-23 11:44 UTC, nikitakaralius requested changes

2024-06-23 11:44 UTC, nikitakaralius commented on src/OnlySpans.PolyLeads.Api/Abstractions/LLM/ILLMClient.cs
> +        string documents,
```suggestion
        IReadOnlyList<string> documentsContent,
```

2024-06-23 11:44 UTC, nikitakaralius commented on src/OnlySpans.PolyLeads.Api/Data/Options/LLMOptions.cs
> +    public string ApiKey { get; init;} = string.Empty;
```suggestion
    public string ApiKey { get; init; } = string.Empty;
```

в остальных местах также

2024-06-23 11:44 UTC, nikitakaralius commented on src/OnlySpans.PolyLeads.Api/Data/Options/LLMOptions.cs
> +    public float Temperature { get; init;} = 0;
а это что такое?

2024-06-23 11:44 UTC, nikitakaralius commented on src/OnlySpans.PolyLeads.Api/Data/Records/LLM/CompletionOptions.cs
> +public sealed record CompletionOptions
Можно сделать их всех `file` и перетянуть в `YandexGptClient`. Больше нигде использоваться не будет, по идее

2024-06-23 11:44 UTC, nikitakaralius commented on src/OnlySpans.PolyLeads.Api/Services/LLM/YandexGptClient.cs
> +        CancellationToken cancellationToken = new CancellationToken())
```suggestion
        CancellationToken cancellationToken = new())
```

2024-06-23 11:44 UTC, nikitakaralius commented on src/OnlySpans.PolyLeads.Api/Services/LLM/YandexGptClient.cs
> +    private readonly IOptions<LLMOptions> _options;
```suggestion
    private readonly LLMOptions>_options;
```

в конструкторе просто `.Value` сразу запишем

2024-06-23 11:44 UTC, nikitakaralius commented on src/OnlySpans.PolyLeads.Api/Services/LLM/YandexGptClient.cs
> +                    Role = "system",
`Role`  кажется в константы куда-нибудь вынести

2024-06-23 11:44 UTC, nikitakaralius commented on src/OnlySpans.PolyLeads.Api/Services/LLM/YandexGptClient.cs
> +        return body;
```suggestion
        return await response
            .Content
            .ReadAsStreamAsync(cancellationToken);
```

2024-06-23 11:44 UTC, nikitakaralius commented on src/OnlySpans.PolyLeads.Api/Services/LLM/YandexGptClient.cs
> +        return body;
это не body просто, а response content

2024-06-23 11:44 UTC, nikitakaralius commented on src/OnlySpans.PolyLeads.Api/Startup/Startup.LLM.cs
> +    private static WebApplicationBuilder AddLLM(this WebApplicationBuilder builder)
```suggestion
    private static WebApplicationBuilder AddLLMIntegration(this WebApplicationBuilder builder)
```

2024-06-23 11:44 UTC, nikitakaralius commented on src/OnlySpans.PolyLeads.Api/appsettings.json
> +  "LLM" : {
здесь все пустыми строчками надо сделать

2024-06-23 11:44 UTC, nikitakaralius commented on src/OnlySpans.PolyLeads.Api/appsettings.Development.json
> +    "FolderId": "b1g3hvvjf8kmmm0p9jjk",
тут уже ключи в коммите засветились, так что болт пока что, но будем менять потом

2024-06-23 11:46 UTC, nikitakaralius requested changes

2024-06-23 11:46 UTC, nikitakaralius commented on src/OnlySpans.PolyLeads.Api/Services/LLM/YandexGptClient.cs
> +        var response = await _httpClient.SendAsync(request, cancellationToken);
Обработка ошибок при сетевом взаимодействии должна обязательно быть

2024-06-23 11:46 UTC, nikitakaralius commented on src/OnlySpans.PolyLeads.Api/Services/LLM/YandexGptClient.cs
> +        var response = await _httpClient.SendAsync(request, cancellationToken);
ExternalServiceFailureException, 424 что ли код

2024-06-23 11:54 UTC, Berkas721 commented on src/OnlySpans.PolyLeads.Api/Data/Options/LLMOptions.cs
> +    public float Temperature { get; init;} = 0;
насколько ответ модели должен соответствовать нашему запросу

2024-06-29 10:26 UTC, nikitakaralius requested changes

2024-06-29 10:26 UTC, nikitakaralius commented on src/OnlySpans.PolyLeads.Api/Services/LLM/YandexGptClient.cs
> +        IReadOnlyList<string> documentsContent,
Наверно, здесь стоит просто `prompt` принимать и как есть в `Text` записывать. А то получается, что мы клиента можем только для документов использовать.

2024-06-29 10:26 UTC, nikitakaralius commented on src/OnlySpans.PolyLeads.Api/Data/Options/LLMOptions.cs
> +public sealed record LLMOptions : IApplicationOptions
```suggestion
public sealed record YandexGptOptions : IApplicationOptions
```

2024-06-29 10:26 UTC, nikitakaralius commented on src/OnlySpans.PolyLeads.Api/Data/Options/LLMOptions.cs
> +    public static string Section { get; } = "LLM";
```suggestion
    public static string Section { get; } = "YandexGpt";
```

2024-06-29 11:37 UTC, nikitakaralius approved these changes

2024-06-29 11:37 UTC, merged